on:
  push:
  pull_request:

name: build
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Set up environment
        run: |
          mkdir ~/bin
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Check out git
        uses: actions/checkout@v3
      - name: install stacker
        run: |
          wget -O ~/bin/stacker https://github.com/project-stacker/stacker/releases/download/v1.0.0-rc2/stacker
          chmod 755 ~/bin/stacker
      - name: make
        run: |
          make bins
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cuddles
          path: bin/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            skopeo
